### PR TITLE
Revised logo in revision directory

### PR DESCRIPTION
**Pull request by examinedliving**
From #8 - I finally got around to doing this.  Sorry for the delay.  See revision directory for new logo files.

### CODE REVIEW

**Comment by examinedliving** [comment]
This is obviously fine with me.  Let me know if you need me to do anything.

**Comment by phated** [comment]
I like @contra's idea.

**Comment by contra** [comment]
@examinedliving Want to make that change in this PR?

**Comment by examinedliving** [comment]
Sure.  Just so I am clear before I do it - your suggesting that I move what I put into the revision folder into a folder called community - correct?  Are there other files that should go in there as well?  Some look obviously community generated, but I just want to make sure I understand correctly.

**Comment by contra** [comment]
@examinedliving All of the current folders (video, wallpaper) should be flattened into the community folder as well.

**Comment by examinedliving** [comment]
@contra See latest commit - if that is consistent with  your intention.

**Comment by phated** [comment]
Looks good.  Thanks!

**Pull request merged**
